name: Workflow 2 - Multi Platform

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: OS info
        run: uname -a
      - name: Create and show file
        run: |
          echo "Hello from Ubuntu" > os-file.txt
          cat os-file.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: OS info
        run: systeminfo
      - name: Create and show file
        shell: powershell
        run: |
          "Hello from Windows" | Out-File -FilePath os-file.txt
          Get-Content os-file.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: OS info
        run: uname -a
      - name: Create and show file
        run: |
          echo "Hello from macOS" > os-file.txt
          cat os-file.txt
